### ISSUE TITLE
How long before a dir gets indexed?

### ISSUE THREAD

**Issue by mhasself** [simonsobs/TeleView#27]
Hi -- Is there a minimum time a directory has to be present before it can be detected and shown in the list?

Until a few minutes ago, the most recent data row was this one:
![image](https://github.com/simonsobs/TeleView/assets/1054988/f2516220-cd78-4d23-be74-988d6af07774)

But all of a sudden it has updated to this one:
![image](https://github.com/simonsobs/TeleView/assets/1054988/fbae0bd2-0fcc-47c1-95a4-c3e259c8eaf0)

And there have been several files, since that just-appeared entry, that aren't showing up yet.  (It is right now 2023-10-11 01:02:00 UTC.)

A bit of delay is ok but it seems like it's taking over 48 hours for data to get indexed!

**Comment by chw3k5** [comment]
## This is not the intended behavior

There is no minimum time designed before an item should be indexed. Indexing occurs every 5 minutes, you should never expect more then a 10 minute delay. Something is wrong. Additionally, directories (and file contents) are re-indexed for 3-days from the current time to allow new files to be added to already indexed directories.


## Paths for a solution

### What I need to be efficient

I only have a hour or so to give to this before next Tuesday, so it is prudent to schedule with me a time that data will be being written so that I can test what is occurring.

It would be good to open the port for MongoDB (27017) so that I can use the [MongDB Compass](https://www.mongodb.com/try/download/compass) GUI for viewing the database during debugging.

There is no need to motivate me with exclamation points, I take issues seriously by default, and I am very sensitive.

### Things you can try

You can manually trigger the 4-indexing types, including a full database reset via the API portal at https://site.simonsobs.org/teleview/api/

Perhaps one can provide a work-around for this problem in the short term?
